### ISSUE TITLE
The circuit for the swichberry

### ISSUE THREAD

**Issue by zyad-elmasri** [drew-wallace/switchberry#1]
For the permaboard, there is a link that shows the circuit, but it is extremely confusing. I noticed that you had a TODO to insert a diagram. I don't know how this website works, and what submitting an issue means, but can you please insert it soon, thank you.

**Comment by viperfx** [comment]
@drew-wallace would also love to know the breadboard layout. A more detailed build guide with pictures would be awesome too.

**Comment by mturley** [comment]
+1 here. Before I set out to replicate this I would love to know exactly what I'm getting into.

**Comment by drew-wallace** [comment]
Updated the readme with the necessary info. I added a picture and Fritzing project file to the [Pictures](https://drive.google.com/drive/folders/0BwfA42Ks3I6nQzBUdE5FRTZLOUU?usp=sharing) shared Google Drive folder.

**Comment by mturley** [comment]
Awesome, thanks so much! That’ll be super helpful.
